### ISSUE TITLE
Crash at startup in 19w13b

### ISSUE THREAD

**Issue by Yanis48** [InsomniaKitten/Couplings#1]
Mappings : 19w13b.3
Fabric API : 0.2.6.117

The game won't start with Couplings installed.
![image](https://user-images.githubusercontent.com/16228338/55280989-df824100-532d-11e9-8537-687ec8db3b94.png)

**Comment by InsomniaKitten** [comment]
Fixed in 1.0.0 **[ [GitHub](https://github.com/InsomniaKitten/Couplings/releases/tag/1.0.0) | [CurseForge](https://minecraft.curseforge.com/projects/couplings/files/2708081) ]**
