### ISSUE TITLE
1.16.4 version

### ISSUE THREAD

**Issue by mainrs** [InsomniaKitten/Couplings#13]
Is there anybody working on a 1.16.4 version? If not would you accept PRs?

**Comment by ChloeDawn** [comment]
Updates targeting 1.16 and 1.17 will be out next week

**Comment by ChloeDawn** [comment]
Couplings is now available for 1.16.5 and 1.17

https://github.com/ChloeDawn/Couplings/releases/tag/1.4.0+1.16 https://www.curseforge.com/minecraft/mc-mods/couplings/files/3374348
https://github.com/ChloeDawn/Couplings/releases/tag/1.4.0+1.17 https://www.curseforge.com/minecraft/mc-mods/couplings/files/3374351
