### ISSUE TITLE
incompatibility with stacc mod

### ISSUE THREAD

**Issue by p1an2ed** [InsomniaKitten/Couplings#16]
When I run minecraft 1.17.1 with stacc, fabric api and couplings I get this error

https://pastebin.ubuntu.com/p/cQTgGxD5yM/

**Comment by ChloeDawn** [comment]
The crash happened during Couplings' mod initialization but is not caused by Couplings. Stacc is failing to find a method target for one of it's mixins, this is exclusively a Stacc bug.
