### ISSUE TITLE
[1.18] Opening waterlogged trapdoors crashes your game.

### ISSUE THREAD

**Issue by ImAK9** [InsomniaKitten/Couplings#17]
https://paste.alloffabric.com/butebiwava.yaml

**Comment by ChloeDawn** [comment]
Couplings does not currently support 1.18, it will be updated soon :)

**Comment by ChloeDawn** [comment]
Couplings is now available for 1.18 ^^

https://github.com/ChloeDawn/Couplings/releases/tag/1.7.1+1.18 | https://www.curseforge.com/minecraft/mc-mods/couplings/files/3554499
