### ISSUE TITLE
Client Crash NoSuchMethodError

### ISSUE THREAD

**Issue by ClaudiusMinimus** [InsomniaKitten/Couplings#18]
I tried to open a trapdoor on in my modpack, [99 Mods on the Wall: Fabric Edition](https://www.curseforge.com/minecraft/modpacks/ninety-nice-99-mods-on-the-wall-fabric-edition/files/3553227) and my client crashed. The server was fine.
 Couplings 1.5.0+1.17
Minecraft 1.18
Fabric 

[crash-2021-12-08_23.07.45-client.txt](https://github.com/ChloeDawn/Couplings/files/7682620/crash-2021-12-08_23.07.45-client.txt)

**Comment by ChloeDawn** [comment]
You are using a 1.17 version of the mod on 1.18, please download the latest version

**Comment by ClaudiusMinimus** [comment]
Did not see you had updated when I made this report. Sorry, and thank you!
CM
