### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Croko1337** [InsomniaKitten/Couplings#2]
https://pastebin.com/WHmFXNFg
fabric-loader-0.4.6+build.141-1.14+build.7
![image](https://user-images.githubusercontent.com/50270059/57180975-b7d74900-6e96-11e9-80a4-2b25f5d38a5b.png)

**Comment by InsomniaKitten** [comment]
Fixed in 1.0.0 **[ [GitHub](https://github.com/InsomniaKitten/Couplings/releases/tag/1.0.0) | [CurseForge](https://minecraft.curseforge.com/projects/couplings/files/2708081) ]**

**Comment by Croko1337** [comment]
Thank you
