### ISSUE TITLE
Doors on servers

### ISSUE THREAD

**Issue by Grovre** [InsomniaKitten/Couplings#20]
Opening doors on servers will cause one to stay closed but seem open, where you just rubberband trying to walk through it

**Comment by ChloeDawn** [comment]
Do you have the mod installed on just the server, or both the server and client? Which version are you using? Do you have any other mods present? If so, which mods?

**Comment by Grovre** [comment]
On the server and client. Turns out the server was using a datapack that
was messing things up.
