### ISSUE TITLE
Villagers are messing with my double doors, leaving one opened/one closed

### ISSUE THREAD

**Issue by calloatti** [InsomniaKitten/Couplings#3]
It seems Villagers are not able to open both doors, so they open just one, and then sometimes bad things happen and one door is left open.

![2019-07-18_13 36 46](https://user-images.githubusercontent.com/12817862/61475530-61d85480-a961-11e9-880f-df467442d381.png)

**Comment by InsomniaKitten** [comment]
Non-player interactions are currently unsupported, I will look into this.

**Comment by InsomniaKitten** [comment]
Implemented in https://github.com/InsomniaKitten/Couplings/commit/ad836d6089413f3f98c6e09a4e10f93239b09216
