### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [InsomniaKitten/Couplings#30]

**Comment by ChloeDawn** [comment]
Does it crash on 1.19.3?

**Comment by sternschnaube** [comment]
Yep, I can provide a bit later the crash log if needed 😊

**Comment by ChloeDawn** [comment]
Fixed in **1.9.2+1.19.3** [ [GitHub](https://github.com/ChloeDawn/Couplings/releases/tag/1.9.2%2B1.19.3) | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/couplings/files/4324077) | [Modrinth](https://modrinth.com/mod/couplings/version/1.9.2%2B1.19.3) ]

**Comment by sternschnaube** [comment]
Thank you so much 🥳
